SELECT 
    dc.REG_ANS, 
    op.Nome_Fantasia,
    dc.DESCRICAO,
    dc.VL_SALDO_FINAL
FROM demonstracoes_contabeis dc
JOIN operadoras op ON dc.REG_ANS = op.Registro_ANS
WHERE dc.DESCRICAO = 'EVENTOS/ SINISTROS CONHECIDOS OU AVISADOS  DE ASSISTÊNCIA A SAÚDE MEDICO HOSPITALAR'
AND dc.PERIODO_TRIMESTRAL = '2024-4'
ORDER BY dc.VL_SALDO_FINAL DESC
LIMIT 10;